### PR TITLE
2nd update to readme

### PR DESCRIPTION
**Pull request by alainlubin**
added instructions to use Instruqt with link

### CODE REVIEW

**Review by kenlangdon — COMMENTED** [review]
Since this is a public facing repo, I wonder if we should leave the instruqt option out since spinning up ephemeral accounts within that platform from that team page is reserved to Lacework team members. The accounts to configure with this can be existing personal, corporate or whatever.

**Comment by TeamWaggles** [comment]
Ah yes, that's a great point.

**Comment by TeamWaggles** [comment]
You can reject this PR.

**Comment by kenlangdon** [comment]
closing per consensus in comments

**Pull request closed without merging**
